#!/bin/bash
#SBATCH -N 1            # number of nodes
#SBATCH -G 0
#SBATCH -c 8            # number of cores 
#SBATCH -t 144:00:00   # time in d-hh:mm:ss
#SBATCH -p public      # partition 
#SBATCH -q public       # QOS
#SBATCH -o slurm.%j.out # file to save job's STDOUT (%j = JobId)
#SBATCH -e slurm.%j.err # file to save job's STDERR (%j = JobId)
#SBATCH --mail-type=ALL # Send an e-mail when a job starts, stops, or fails
#SBATCH --mail-user="%u@asu.edu"
#SBATCH --export=NONE   # Purge the job-submitting shell environment

#Load required software
module load mamba/latest

#Activate our enviornment
source activate geomain

#Change to the directory of our script
cd /home/hbaier/packages/geoetl

#Run the software/python script
geoetl --config /home/hbaier/packages/geoetl/configs/ohio2020.yml

