aoi:
  path: /home/hbaier/projects/tlags_v2/data/tracts2019/AZ/tl_2019_04_tract_wi.shp

catalog:
  sensor: mpc_sentinel2
  start_date: "2016-01-01"
  end_date: "2016-03-31"
  cloud_cover_max: 30
  mask_clouds: false

auth:
  mpc_api_key: null

output:
  root: /data/hbaier/new_data/tlag/az_imagery/q1_2016_s2/
  sub_root: False
  format: png
  png_scale_mode: auto

params:
  uid_column: GEOID
  label_column: wealth_ind
  dataset_name: az_2016_q1_s2