aoi:
  path: /scratch/hbaier/new_data/usaid_dhs/indicators/point_buffers/all_vars_og_point_buffers.shp

catalog:
  sensor: planet
  composite: global_quarterly_2022q3_mosaic

auth:
  api_key: ${PLANET_API_KEY}   # or just put the key string here

output:
  root: /scratch/hbaier/new_data/usaid_dhs/imagery
  sub_root: False

params:
  uid_column: geo_id
  label_column: label
  dataset_name: phl_gee_test