aoi:
  path: /data/hbaier/new_data/tlag/year_shps/2020_census.shp

catalog:
  sensor: landsat8
  composite: "LANDSAT/LC08/C02/T1_L2"
  year: 2020
  start_date: "2020-01-01"
  end_date: "2020-12-31"
  
auth:
  api_key: ${PLANET_API_KEY}   # or just put the key string here

output:
  root: /data/hbaier/new_data/tlag/imagery/2020/
  sub_root: False
  
params:
  uid_column: GEOID
  label_column: poverty_ra
  dataset_name: ohio2020




# {
#   "catalog": { "sensor": "landsat", "year": 2020, "month": 8 },
#   "auth": { "ee_project": "your-gee-project-id" },
#   "output": { "root": "/path/to/output" }
# }