aoi:
  path: /data/hbaier/new_data/tlag/year_shps/2023_census.shp

catalog:
  sensor: mpc_landsat8
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  cloud_cover_max: 30
  mask_clouds: false

auth:
  mpc_api_key: null

output:
  root: /data/hbaier/new_data/tlag/imagery/2023/
  sub_root: False

params:
  uid_column: GEOID
  label_column: poverty_ra
  dataset_name: ohio2023
