aoi:
  path: /home/hbaier/projects/sr/dl_imagery/geoetl/data/phl_1p5km_buffers.shp

catalog:
  sensor: planet
  composite: global_quarterly_2022q3_mosaic

auth:
  api_key: ${PLANET_API_KEY}   # or just put the key string here

output:
  root: /scratch/hbaier/new_data/phl_temporal/imagery
  sub_root: False

params:
  uid_column: geo_id
  label_column: label
  dataset_name: phl_gee_test
  
temporal:
  enabled: true
  cadence: quarterly
  years: [2022, 2023]
  steps: [1, 2, 3, 4]
